### ISSUE TITLE
feat: 실시간 검색 기능 구현

### ISSUE THREAD

**Issue by KarmaPol** [Team-BingBong/BE-05-Bingterpark#151]
## 요약
실시간 검색 기능 구현

## 기능 상세
- [ ] 실시간 검색 기능 구현

**Comment by KarmaPol** [comment]
### 실시간 검색 기능 참고 블로그
https://velog.io/@dktlsk6/Spring-boot-ElasticSearch-%EC%97%B0%EB%8F%99-%ED%95%98%EC%97%AC-%EC%8B%A4%EC%8B%9C%EA%B0%84-%EA%B2%80%EC%83%89-%EC%88%9C%EC%9C%84-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0

**Comment by KarmaPol** [comment]
### 로그 스태시 정리
https://justdoit0730.tistory.com/126

**Comment by KarmaPol** [comment]
### SearchHit Aggregation(집계) 가져오기
https://stackoverflow.com/questions/76280992/spring-data-elasticsearch-4-4-x-how-to-get-aggregations-from-searchhits

**Comment by park0jae** [comment]
### Aggregation 내의 Script 정의 정리
https://discuss.elastic.co/t/high-priority-how-to-add-subaggregtion-in-terms-aggregation-for-spring-data-elasticsearch-5-1/344015
